dist: xenial
language: java
env:
- BUILD_DIR="~/builds/backend-test/"
addons:
  sonarcloud:
    organization: nickmanbear
    token:
      secure: IN0V3NSKaBp5NqSJFtbt+5A9M3AwxE8lfpac+WewiEE7yFQ5paHTq7a2+RdG0sLW0LcQUtZeGS4ryYyBG3oPR01CVab/oSlwyv1deQY0oZzMPo8qRn2uy4doV6VTYjBkihvkN6tiJn6Ht2leR9l2yhpHiI50OqjCxu8TZj077Qnu8AGRxpE+V20UpVUoaCuuSU7kSUbCxQMtcntKjH6iGeW07WPZC13EnuKe2+tQLl3spxCTE/XswfMuSLfP9Hb0TSvka+cVbJk1J9FLqMOiLC4y+CfYejr4n5LAwGUnxnW/cds+iQOyoRtpKD0pcGgDZtHmKpl5n114x9ZOuzeOEf89TKqhmG//NgI2zTmcHClgpjbkXcljc/XXRYL66ZJh0a1lm/v1HENR6JYv+SduZx3stn8tI60MKDTnyplLsohm8xZEPvaNpxcQz8B1CD5WYniaLbvzhq9BcU3q5FnqXdivMh59AdwaMbAIsItFRWF6suKXh8HqjKIdTgSPiqyqvWbPOyGYLBfoWsSg6rrGthYPpC6Id7x04Qzk0HpxW7HYeepdL6lgNAlVLbluEMbqMGelBuPEUk8CW29wU4Stlnl1xIeFHoHURCud/Xok73Hucax/ABakqvrdIPV9CRDkQsLyML+mY8k4dYz8RHaQGgEvsq5LZnvYPcD7LRuao90=
before_install:
- openssl aes-256-cbc -K $encrypted_c28ab4f155ee_key -iv $encrypted_c28ab4f155ee_iv
  -in id_rsa-travis-ci.enc -out id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./id_rsa
- echo -e "Host swarm.cherement.nl\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo $BUILD_DIR
- ssh -i ./id_rsa travis-ci@swarm.cherement.nl pwd
- docker login swarm.cherement.nl:5000 -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install:
- "./gradlew build"
services:
- docker
jobs:
  include:
  - stage: Tests
    script: "./gradlew test"
    script: "./gradlew sonarqube"
  - stage: Deployment-Test.server
    if: branch = dev
    deploy:
    provider: script
    skip_cleanup: true
    script: bash  ".travis/deploy-test.sh"
    on:
      branch: dev 
  - stage: Deployment-prod.server
    if: branch = master
    env:
    - BUILD_DIR="~/builds/backend-prod/"
    deploy:
      provider: script
      skip_cleanup: true 
      script: bash ".travis/deploy-prod.sh"
      on:
        branch: master
